language: go

go:
  - "1.11.x"

env:
  global:
    - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin latest
  - golangci-lint --version

install:
  - go mod download

script:
  golangci-lint run